### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Mariobai** [yongyehuang/view_based_sentiment#1]
您好，你能够提供一下您view_based_sentiment这个项目中的词向量训练的语料库吗?因为您说了你这个是训练数据测试数据和网上抓取的汽车评论数据。这个数据能够提供一下吗？谢谢，
我的邮箱：503373015@qq.com

**Comment by yongyehuang** [comment]
@JinJiao8 你好，我抓取的评论数据都放在 comments 文件夹下面呢，你可以直接下载。

**Comment by Mariobai** [comment]
谢谢您。
